# server/config/prod.yaml
env: "dev"

http_server:
  address: "0.0.0.0:8080" # Render ожидает, что приложение будет слушать на этом адресе
  timeout: 10s
  idle_timeout: 120s
  allowed_origins:
    # <<< ИЗМЕНЕНИЕ: URL вашего фронтенда на Vercel >>>
    - "https://todo-rho-sage.vercel.app"
  tls:
    # <<< ИЗМЕНЕНИЕ: TLS/HTTPS будет обрабатывать Render >>>
    enabled: false
    # cert_file и key_file не нужны

fcm_config:
  project_id: "todo-80b1b"
  service_account_key_json_path: "/app/todo-80b1b-firebase-adminsdk-fbsvc-6f38d4c04c.json"

db:
  # <<< ИЗМЕНЕНИЕ: Данные из вашего PostgreSQL на Render >>>
  username: "user"
  host: "dpg-d13vft8gjchc73fk5sqg-a.oregon-postgres.render.com" # Внешний хост для Render
  port: "5432"
  dbname: "todo_uk2f"
  ssl_mode: "require" # Render требует SSL

cache:
  # <<< ИЗМЕНЕНИЕ: Адрес из вашего Redis на Render >>>
  address: "red-d13vg3e3jp1c73dgeb20:6379" # Внутренний адрес Render
  db: 0
  state_expiration: 5m
  email_confirmed_code_expiration: 16m
  default_task_cache_ttl: 15m
  default_team_cache_ttl: 15m
  default_team_list_cache_ttl: 5m

s3:
  endpoint: "storage-321.s3hoster.by"
  region: "BTC"
  bucket_user_avatars: "useravatar"
  bucket_team_images: "teamimages"
  max_team_image_size_bytes: 5242880

smtp:
  host: "smtp.yandex.ru"
  port: 587
  username: "ToDoAppResp@yandex.by"

jwt:
  access_expire: 12h
  refresh_expire: 168h
  # <<< ИЗМЕНЕНИЕ: Настройки cookie для продакшена >>>
  secure_cookie: true
  cookie_domain: "todo-vd2m.onrender.com" # Домен вашего бэкенда

oauth:
  # <<< URL для ВЕБ-клиентов (редирект на фронтенд) >>>
  google_redirect_url: "https://todo-rho-sage.vercel.app/oauth/callback/google"
  yandex_redirect_url: "https://todo-rho-sage.vercel.app/oauth/callback/yandex"

  # <<< URL для НАТИВНЫХ клиентов (редирект на бэкенд) >>>
  google_redirect_url_native: "https://todo-vd2m.onrender.com/v1/auth/google/callback"
  yandex_redirect_url_native: "https://todo-vd2m.onrender.com/v1/auth/yandex/callback"

  # URL'ы для финального редиректа после успешного/неуспешного логина
  frontend_redirect_success_url: "https://todo-rho-sage.vercel.app/"
  frontend_redirect_error_url: "https://todo-rho-sage.vercel.app/auth?error=true"