// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2EUCjMwTprnTgri-JTQys16xQtmso68',
    appId: '1:584852511104:web:f8add5e513f822d1c78965',
    messagingSenderId: '584852511104',
    projectId: 'todo-80b1b',
    authDomain: 'todo-80b1b.firebaseapp.com',
    storageBucket: 'todo-80b1b.firebasestorage.app',
    measurementId: 'G-NFB05DVM3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWtKE4sI647T1kt6NsDfmAc8v8sKneTmA',
    appId: '1:584852511104:android:57ef356aee86c672c78965',
    messagingSenderId: '584852511104',
    projectId: 'todo-80b1b',
    storageBucket: 'todo-80b1b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR2EUCjMwTprnTgri-JTQys16xQtmso68',
    appId: '1:584852511104:web:ea1f9766efa67990c78965',
    messagingSenderId: '584852511104',
    projectId: 'todo-80b1b',
    authDomain: 'todo-80b1b.firebaseapp.com',
    storageBucket: 'todo-80b1b.firebasestorage.app',
    measurementId: 'G-FRJV9GYPHW',
  );

}