# .github/workflows/build-release.yml
name: Build & Release Flutter App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release AppImage
    runs-on: ubuntu-latest

    steps:
      # 1. Загружаем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. Устанавливаем системные зависимости, которые нужны для сборки и работы AppImage
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libsecret-1-dev libappindicator3-dev fuse

      # 4. Устанавливаем flutter_to_appimage
      - name: Install flutter_to_appimage
        run: |
          # Скачиваем и устанавливаем последнюю версию из репозитория
          wget "https://github.com/ubuntu-flutter-community/flutter_to_appimage/releases/latest/download/flutter_to_appimage-linux.tar.gz"
          tar -xzf flutter_to_appimage-linux.tar.gz
          sudo mv flutter_to_appimage /usr/local/bin/

      # 5. Запускаем сборку AppImage
      # Инструмент сам вызовет 'flutter build' и упакует все необходимое.
      # Он работает из корня Flutter-проекта.
      - name: Build AppImage
        run: flutter_to_appimage
        working-directory: ./client # Указываем, где находится наш Flutter-проект

      # 6. Создаем релиз и загружаем готовый файл
      # Файл будет находиться в client/dist/
      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: client/dist/*.AppImage