# .github/workflows/fastforge_release.yml

name: Fastforge Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Устанавливаем Flutter (необходимо для fastforge)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Устанавливаем fastforge
      - name: Activate fastforge
        run: dart pub global activate fastforge

      # Запускаем сборку и релиз ОДНОЙ КОМАНДОЙ
      - name: Build and Release with fastforge
        # Указываем, что проект находится в папке client
        working-directory: ./client
        run: fastforge release --github-token ${{ secrets.GITHUB_TOKEN }}