version: 1

script:
  # Этот скрипт будет выполняться из корня Flutter-проекта (`client/`)
  - rm -rf AppDir || true
  - mkdir -p AppDir
  # Копируем содержимое скомпилированного бандла в AppDir
  - cp -r build/linux/x64/release/bundle/* AppDir/
  # Копируем иконку. Имя иконки должно совпадать с ключом 'icon' в app_info.
  - cp appimage_builder/client.png AppDir/
  # Копируем desktop-файл
  - cp appimage_builder/client.desktop AppDir/

AppDir:
  path: ./AppDir

  app_info:
    id: com.yourcompany.todo
    name: ToDo
    icon: client # Имя файла иконки БЕЗ расширения
    version: 1.0.0 # Версия будет заменена в CI
    exec: client # Исполняемый файл теперь в корне AppDir
    exec_args: $@

  # Используем apt для зависимостей, как в официальном примере,
  # это самый надежный метод для CI
  apt:
    arch: amd64
    sources:
      - sourceline: "deb [trusted=yes] http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse"
    include:
      - libgtk-3-0
      - libsecret-1-0
      - libnotify4
      - libayatana-appindicator3-1

  # Эта секция необязательна, но полезна для уменьшения размера
  files:
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*

AppImage:
  arch: x86_64
  update-information: guess
  sign-key: None