# .github/workflows/release.yml

name: Fastforge Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    # Важно: fastforge сам управляет сборкой на разных ОС.
    # Для Windows/macOS он может использовать сторонние сервисы (например, Codemagic),
    # но для Linux/Android/Web достаточно ubuntu-latest.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Устанавливаем Flutter (необходимо для fastforge)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Устанавливаем fastforge
      - name: Activate fastforge
        run: dart pub global activate fastforge

      # Запускаем сборку и релиз ОДНОЙ КОМАНДОЙ
      - name: Build and Release with fastforge
        # Указываем, что наш Flutter-проект находится в папке client/
        working-directory: ./client
        # 1. Запускаем релиз с именем 'production' из distribute_options.yaml
        # 2. Передаем GITHUB_TOKEN как переменную окружения
        run: fastforge release --name production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}