# .github/workflows/build-release.yml
name: Build & Release Flutter App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build Linux AppImage (x86_64)
    runs-on: ubuntu-latest

    steps:
      # 1. Загружаем код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3. ИСПРАВЛЕНИЕ: Устанавливаем полный набор зависимостей
      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libsecret-1-dev libappindicator3-dev

      # 4. Собираем Linux билд
      - name: Build Flutter Linux
        run: flutter build linux --target-platform=linux-x64
        working-directory: ./client

      # 5. Устанавливаем инструмент для сборки AppImage
      - name: Download appimage-builder
        run: |
          wget https://github.com/AppImage/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage -O appimage-builder
          chmod +x appimage-builder
          sudo mv appimage-builder /usr/local/bin/

      # 6. Создаем рецепт для AppImage на лету
      - name: Create AppImage Recipe
        run: |
          cat > appimage-builder.yml <<EOF
          version: 1
          script:
            - cp -r client/build/linux/x64/release/bundle/* AppDir/
            - cp client/assets/icons/logo.svg AppDir/com.yourcompany.todo.svg
            - cp client/appimage_builder/client.desktop AppDir/com.yourcompany.todo.desktop

          AppDir:
            path: \$(pwd)/AppDir
            app_info:
              id: com.yourcompany.todo
              name: ToDo
              icon: com.yourcompany.todo
              version: ${{ github.ref_name }}
              exec: client
            apt:
              arch: amd64
              sources:
                - sourceline: "deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse"
              include:
                - libgtk-3-0
                - libsecret-1-0
                - libnotify4
                - libayatana-appindicator3-1
          
          AppImage:
            arch: x86_64
            update-information: "gh-releases-zsync|DIIASA|ToDo|latest|ToDo-*-x86_64.AppImage.zsync"
          EOF

      # 7. Запускаем сборку AppImage
      - name: Build AppImage
        run: appimage-builder --recipe appimage-builder.yml

      # 8. Переименовываем артефакт для релиза
      - name: Rename Artifact
        run: mv ToDo-*.AppImage ToDo-${{ github.ref_name }}-Linux-x86_64.AppImage

      # 9. Создаем релиз и загружаем в него AppImage
      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ToDo-*.AppImage